services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mw-web
        image: mw-web
        restart: unless-stopped
        ports:
            - "7000:3000"
        healthcheck:
            test: ["CMD", "curl", "-f", "-I", "http://localhost:3000"]
            interval: 5m
            timeout: 10s
            retries: 3
        volumes:
            - ./.next/cache:/app/.next/cache
            - ./.env:/app/.env
        dns:
            - 1.1.1.1
            - 8.8.8.8
            - 9.9.9.9
